CREATE TABLE IF NOT EXISTS category (
    id BIGINT NOT NULL UNIQUE,
    guid UUID NOT NULL PRIMARY KEY,
    name VARCHAR (255) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIMEZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIMEZONE NOT NULL DEFAULT NOW()
);
--bun:split

CREATE TABLE IF NOT EXISTS product (
    id BIGINT NOT NULL UNIQUE,
    guid UUID NOT NULL PRIMARY KEY,
    name VARCHAR NOT NULL UNIQUE,
    description VARCHAR (255) DEFAULT NULL,
    price DECIMAL(12,3) NOT NULL,
    category_guid UUID NOT NULL FOREIGN KEY REFERENCES categories(guid) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIMEZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIMEZONE NOT NULL DEFAULT NOW()
);